create table instrument_takes (
	student_id int NOT NULL REFERENCES student,
	instrument_uses VARCHAR(15)
);
insert into instrument_takes (student_id, instrument_uses) values (1, 'flute');
insert into instrument_takes (student_id, instrument_uses) values (2, 'piano');
insert into instrument_takes (student_id, instrument_uses) values (3, 'flute & guitar');
insert into instrument_takes (student_id, instrument_uses) values (4, 'violin');
insert into instrument_takes (student_id, instrument_uses) values (5, 'violin & guitar');
insert into instrument_takes (student_id, instrument_uses) values (6, 'flute');
insert into instrument_takes (student_id, instrument_uses) values (7, 'violin');
insert into instrument_takes (student_id, instrument_uses) values (8, 'flute');
insert into instrument_takes (student_id, instrument_uses) values (9, 'flute');
insert into instrument_takes (student_id, instrument_uses) values (10, 'flute & guitar');
insert into instrument_takes (student_id, instrument_uses) values (11, 'flute & guitar');
insert into instrument_takes (student_id, instrument_uses) values (12, 'piano');
insert into instrument_takes (student_id, instrument_uses) values (13, 'piano');
insert into instrument_takes (student_id, instrument_uses) values (14, 'violin & guitar');
insert into instrument_takes (student_id, instrument_uses) values (15, 'flute');
insert into instrument_takes (student_id, instrument_uses) values (16, 'flute & piano');
insert into instrument_takes (student_id, instrument_uses) values (17, 'trumpet');
insert into instrument_takes (student_id, instrument_uses) values (18, 'violin & guitar');
insert into instrument_takes (student_id, instrument_uses) values (19, 'guitar');
insert into instrument_takes (student_id, instrument_uses) values (20, 'piano');
insert into instrument_takes (student_id, instrument_uses) values (21, 'flute & piano');
insert into instrument_takes (student_id, instrument_uses) values (22, 'piano');
insert into instrument_takes (student_id, instrument_uses) values (23, 'guitar');
insert into instrument_takes (student_id, instrument_uses) values (24, 'violin');
insert into instrument_takes (student_id, instrument_uses) values (25, 'flute & piano');
insert into instrument_takes (student_id, instrument_uses) values (26, 'flute');
insert into instrument_takes (student_id, instrument_uses) values (27, 'flute & piano');
insert into instrument_takes (student_id, instrument_uses) values (28, 'guitar');
insert into instrument_takes (student_id, instrument_uses) values (29, 'trumpet');
insert into instrument_takes (student_id, instrument_uses) values (30, 'flute & piano');
insert into instrument_takes (student_id, instrument_uses) values (31, 'guitar');
insert into instrument_takes (student_id, instrument_uses) values (32, 'trumpet');
insert into instrument_takes (student_id, instrument_uses) values (33, 'flute & guitar');
insert into instrument_takes (student_id, instrument_uses) values (34, 'violin & guitar');
insert into instrument_takes (student_id, instrument_uses) values (35, 'guitar');
insert into instrument_takes (student_id, instrument_uses) values (36, 'flute & guitar');
insert into instrument_takes (student_id, instrument_uses) values (37, 'guitar');
insert into instrument_takes (student_id, instrument_uses) values (38, 'piano');
insert into instrument_takes (student_id, instrument_uses) values (39, 'flute');
insert into instrument_takes (student_id, instrument_uses) values (40, 'flute');
insert into instrument_takes (student_id, instrument_uses) values (41, 'flute & piano');
insert into instrument_takes (student_id, instrument_uses) values (42, 'trumpet & piano');
insert into instrument_takes (student_id, instrument_uses) values (43, 'trumpet');
insert into instrument_takes (student_id, instrument_uses) values (44, 'flute');
insert into instrument_takes (student_id, instrument_uses) values (45, 'trumpet & piano');
insert into instrument_takes (student_id, instrument_uses) values (46, 'trumpet & piano');
insert into instrument_takes (student_id, instrument_uses) values (47, 'flute');
insert into instrument_takes (student_id, instrument_uses) values (48, 'trumpet & piano');
insert into instrument_takes (student_id, instrument_uses) values (49, 'piano');
insert into instrument_takes (student_id, instrument_uses) values (50, 'piano');
insert into instrument_takes (student_id, instrument_uses) values (51, 'violin & guitar');
insert into instrument_takes (student_id, instrument_uses) values (52, 'flute & guitar');
insert into instrument_takes (student_id, instrument_uses) values (53, 'guitar');
insert into instrument_takes (student_id, instrument_uses) values (54, 'flute & piano');
insert into instrument_takes (student_id, instrument_uses) values (55, 'guitar');
insert into instrument_takes (student_id, instrument_uses) values (56, 'violin');
insert into instrument_takes (student_id, instrument_uses) values (57, 'violin & guitar');
insert into instrument_takes (student_id, instrument_uses) values (58, 'flute & guitar');
insert into instrument_takes (student_id, instrument_uses) values (59, 'guitar');
insert into instrument_takes (student_id, instrument_uses) values (60, 'violin & guitar');
insert into instrument_takes (student_id, instrument_uses) values (61, 'violin');
insert into instrument_takes (student_id, instrument_uses) values (62, 'trumpet');
insert into instrument_takes (student_id, instrument_uses) values (63, 'trumpet & piano');
insert into instrument_takes (student_id, instrument_uses) values (64, 'flute & piano');
insert into instrument_takes (student_id, instrument_uses) values (65, 'flute & guitar');
insert into instrument_takes (student_id, instrument_uses) values (66, 'guitar');
insert into instrument_takes (student_id, instrument_uses) values (67, 'guitar');
insert into instrument_takes (student_id, instrument_uses) values (68, 'trumpet');
insert into instrument_takes (student_id, instrument_uses) values (69, 'violin');
insert into instrument_takes (student_id, instrument_uses) values (70, 'piano');
insert into instrument_takes (student_id, instrument_uses) values (71, 'trumpet & piano');
insert into instrument_takes (student_id, instrument_uses) values (72, 'trumpet & piano');
insert into instrument_takes (student_id, instrument_uses) values (73, 'flute & piano');
insert into instrument_takes (student_id, instrument_uses) values (74, 'violin & guitar');
insert into instrument_takes (student_id, instrument_uses) values (75, 'piano');
insert into instrument_takes (student_id, instrument_uses) values (76, 'flute');
insert into instrument_takes (student_id, instrument_uses) values (77, 'violin & guitar');
insert into instrument_takes (student_id, instrument_uses) values (78, 'piano');
insert into instrument_takes (student_id, instrument_uses) values (79, 'guitar');
insert into instrument_takes (student_id, instrument_uses) values (80, 'trumpet');
insert into instrument_takes (student_id, instrument_uses) values (81, 'piano');
insert into instrument_takes (student_id, instrument_uses) values (82, 'trumpet');
insert into instrument_takes (student_id, instrument_uses) values (83, 'violin & guitar');
insert into instrument_takes (student_id, instrument_uses) values (84, 'guitar');
insert into instrument_takes (student_id, instrument_uses) values (85, 'trumpet');
insert into instrument_takes (student_id, instrument_uses) values (86, 'flute & guitar');
insert into instrument_takes (student_id, instrument_uses) values (87, 'piano');
insert into instrument_takes (student_id, instrument_uses) values (88, 'flute');
insert into instrument_takes (student_id, instrument_uses) values (89, 'violin & guitar');
insert into instrument_takes (student_id, instrument_uses) values (90, 'violin');
insert into instrument_takes (student_id, instrument_uses) values (91, 'piano');
insert into instrument_takes (student_id, instrument_uses) values (92, 'trumpet & piano');
insert into instrument_takes (student_id, instrument_uses) values (93, 'violin');
insert into instrument_takes (student_id, instrument_uses) values (94, 'flute & piano');
insert into instrument_takes (student_id, instrument_uses) values (95, 'guitar');
insert into instrument_takes (student_id, instrument_uses) values (96, 'violin & guitar');
insert into instrument_takes (student_id, instrument_uses) values (97, 'trumpet & piano');
insert into instrument_takes (student_id, instrument_uses) values (98, 'violin & guitar');
insert into instrument_takes (student_id, instrument_uses) values (99, 'flute & guitar');
insert into instrument_takes (student_id, instrument_uses) values (100, 'violin');
