create table instrument_type_teaches (
	instructor_id int NOT NULL REFERENCES instructor,
	instrument_teaches_type VARCHAR(15)
);
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (1, 'piano & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (2, 'guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (3, 'flute & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (4, 'violin & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (5, 'flute & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (6, 'flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (7, 'violin & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (8, 'piano & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (9, 'flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (10, 'flute & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (11, 'violin');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (12, 'piano & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (13, 'flute & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (14, 'piano');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (15, 'violin & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (16, 'piano & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (17, 'piano & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (18, 'piano');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (19, 'flute & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (20, 'flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (21, 'violin & flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (22, 'piano & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (23, 'violin');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (24, 'piano & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (25, 'violin & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (26, 'violin & flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (27, 'violin');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (28, 'flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (29, 'violin & flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (30, 'flute & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (31, 'piano');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (32, 'flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (33, 'piano & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (34, 'flute & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (35, 'violin');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (36, 'violin & flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (37, 'piano');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (38, 'piano');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (39, 'violin');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (40, 'flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (41, 'flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (42, 'flute & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (43, 'violin & flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (44, 'guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (45, 'flute & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (46, 'flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (47, 'violin');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (48, 'violin & flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (49, 'violin');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (50, 'piano');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (51, 'flute & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (52, 'violin & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (53, 'piano');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (54, 'violin & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (55, 'piano & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (56, 'flute & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (57, 'flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (58, 'piano');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (59, 'piano & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (60, 'piano');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (61, 'guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (62, 'piano & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (63, 'flute & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (64, 'violin');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (65, 'guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (66, 'flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (67, 'violin & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (68, 'violin & flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (69, 'guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (70, 'flute & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (71, 'piano & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (72, 'guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (73, 'piano');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (74, 'violin & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (75, 'violin & flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (76, 'violin & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (77, 'violin & flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (78, 'piano & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (79, 'violin');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (80, 'violin & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (81, 'violin & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (82, 'flute & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (83, 'piano & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (84, 'violin & flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (85, 'flute & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (86, 'violin & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (87, 'violin');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (88, 'flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (89, 'flute & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (90, 'violin & flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (91, 'piano & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (92, 'guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (93, 'guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (94, 'violin & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (95, 'flute & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (96, 'violin & flute');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (97, 'violin');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (98, 'piano & guitar');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (99, 'piano');
insert into instrument_type_teaches (instructor_id, instrument_teaches_type) values (100, 'piano & guitar');
